### ISSUE TITLE
issue: About model configuration

### ISSUE THREAD

**Issue by dinream** [Suxyuuu/PagPassGPT#2]
hi，

In Paper, it shows configuration :
![image](https://github.com/user-attachments/assets/aae36afa-9227-4725-b457-816b642b8e51)

but in [train.py](https://github.com/Suxyuuu/PagPassGPT/blob/main/train.py), the configuration as shown below:

```python
parser.add_argument("--layer_num", help="num of layers", type=int, default=8)
parser.add_argument("--head_num", help="num of multi head", type=int, default=12)
```
Which standard should I use?

**Comment by Suxyuuu** [comment]
follow the paper.

**Comment by dinream** [comment]
OK, thank you very much for your answer
